name: Documentation

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fix Deployment for GH Pages
        run: mkdir -p _build/dirhtml/ && touch _build/dirhtml/.nojekyll
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - run: pip install -r requirements.txt
      - run: make html dirhtml

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: _build/dirhtml/
          clean: true


